import { Assignment } from "@/lib/types";

export const assignments: Assignment[] = [
  {
    id: "asg-1",
    title: "Trigonometric Identities Worksheet",
    subject: "Mathematics",
    dueDate: "2026-07-21",
    status: "pending",
  },
  {
    id: "asg-2",
    title: "Laws of Motion - Problem Set",
    subject: "Physics",
    dueDate: "2026-07-18",
    status: "graded",
    score: 42,
    maxScore: 50,
  },
  {
    id: "asg-3",
    title: "Redox Reactions Lab Report",
    subject: "Chemistry",
    dueDate: "2026-07-23",
    status: "pending",
  },
  {
    id: "asg-4",
    title: "Essay: The Portrait of a Lady",
    subject: "English",
    dueDate: "2026-07-16",
    status: "overdue",
  },
  {
    id: "asg-5",
    title: "Cell Structure Diagram Labeling",
    subject: "Biology",
    dueDate: "2026-07-25",
    status: "submitted",
  },
  {
    id: "asg-6",
    title: "Sets & Relations Quiz Prep",
    subject: "Mathematics",
    dueDate: "2026-07-14",
    status: "graded",
    score: 18,
    maxScore: 20,
  },
  // Personalized assignments generated to target the same weak concepts
  // surfaced on /weak-areas, so both pages stay consistent.
  {
    id: "asg-7",
    title: "Targeted Practice: Permutations",
    subject: "Mathematics",
    dueDate: "2026-07-22",
    status: "pending",
    targetConcept: "Permutations",
    bloomLevel: "Apply",
    questionCount: 12,
    personalized: true,
  },
  {
    id: "asg-8",
    title: "Targeted Practice: Ellipse & Hyperbola",
    subject: "Mathematics",
    dueDate: "2026-07-24",
    status: "pending",
    targetConcept: "Ellipse & Hyperbola",
    bloomLevel: "Apply",
    questionCount: 10,
    personalized: true,
  },
  {
    id: "asg-9",
    title: "Targeted Practice: Friction",
    subject: "Physics",
    dueDate: "2026-07-23",
    status: "pending",
    targetConcept: "Friction",
    bloomLevel: "Apply",
    questionCount: 10,
    personalized: true,
  },
  {
    id: "asg-10",
    title: "Targeted Practice: Balancing Redox Equations",
    subject: "Chemistry",
    dueDate: "2026-07-20",
    status: "overdue",
    targetConcept: "Balancing Redox Equations",
    bloomLevel: "Apply",
    questionCount: 8,
    personalized: true,
  },
  {
    id: "asg-11",
    title: "Targeted Practice: Biomolecules",
    subject: "Biology",
    dueDate: "2026-07-17",
    status: "graded",
    score: 32,
    maxScore: 40,
    targetConcept: "Biomolecules",
    bloomLevel: "Analyze",
    questionCount: 8,
    personalized: true,
  },
];
