import { LessonPlan, LessonQuestion } from "@/lib/types";
import { getTopicContent } from "@/lib/mock-data/topic-content";

const authoredLessons: Record<string, LessonQuestion[]> = {
  "math-t1": [
    {
      id: "math-t1-l1a",
      bloomLevel: 1,
      type: "mcq",
      prompt: "Which of the following is an example of the empty set?",
      options: ["{0}", "{x : x is a natural number less than 1}", "{1, 2, 3}", "{x : x is a vowel}"],
      correctAnswer: "{x : x is a natural number less than 1}",
      explanation: "There is no natural number less than 1 (natural numbers start at 1), so this set has no elements — it is the empty set ∅. {0} is NOT empty; it contains one element, the number 0.",
      reteach: "Remember: the empty set ∅ has zero elements. {0} is a set containing the number 0 — that's one element, not zero! Look for a condition that literally cannot be satisfied by any number.",
      hint: "Ask: can any natural number actually satisfy 'less than 1'?",
      xp: 10,
    },
    {
      id: "math-t1-l1b",
      bloomLevel: 1,
      type: "true-false",
      prompt: "The set A = {1, 2, 2, 3} has exactly 4 elements.",
      correctAnswer: "False",
      explanation: "Sets only count distinct elements — repeated elements are listed once. So A = {1, 2, 3}, which has exactly 3 elements, not 4.",
      reteach: "A set never repeats elements. Even if '2' is written twice, it only counts once. Rewrite the set without repeats before counting.",
      hint: "Do sets allow duplicate elements?",
      xp: 10,
    },
    {
      id: "math-t1-l2a",
      bloomLevel: 2,
      type: "mcq",
      prompt: "If A = {2, 4, 6} and B = {1, 2, 3}, what is A ∩ B?",
      options: ["{2}", "{1, 2, 3, 4, 6}", "{4, 6}", "∅"],
      correctAnswer: "{2}",
      explanation: "The intersection contains only elements common to BOTH sets. The only number appearing in both A and B is 2.",
      reteach: "Intersection = 'AND' — an element must be in set A AND set B. Go through B's elements and check which ones also appear in A.",
      hint: "Which single number appears in both lists?",
      xp: 15,
    },
    {
      id: "math-t1-l2b",
      bloomLevel: 2,
      type: "fill-blank",
      prompt: "If U = {1, 2, 3, 4, 5} and A = {1, 2}, then A′ (complement of A) = ___",
      correctAnswer: "{3,4,5}",
      explanation: "The complement of A contains everything in U that is NOT in A. Removing 1 and 2 from U leaves {3, 4, 5}.",
      reteach: "Complement = 'everything else in U'. List all elements of U, then cross out those in A — what remains is A′.",
      hint: "Start with U and remove A's elements.",
      xp: 15,
    },
    {
      id: "math-t1-l3a",
      bloomLevel: 3,
      type: "mcq",
      prompt: "A class has 30 students; 18 play cricket, 15 play football, and 8 play both. How many play neither sport?",
      options: ["5", "8", "25", "3"],
      correctAnswer: "5",
      explanation: "n(A∪B) = n(A)+n(B)−n(A∩B) = 18+15−8 = 25 play at least one sport. Neither = 30 − 25 = 5.",
      reteach: "First find how many play AT LEAST ONE sport using the union formula, subtracting the overlap once. Then subtract that total from the class size to get 'neither'.",
      hint: "Use n(A∪B) = n(A) + n(B) − n(A∩B), then subtract from the total.",
      xp: 20,
    },
    {
      id: "math-t1-l3b",
      bloomLevel: 3,
      type: "short-answer",
      prompt: "Write the set-builder form of A = {2, 4, 6, 8, 10}.",
      correctAnswer: "A = {x : x = 2n, n is a natural number, 1 ≤ n ≤ 5}",
      explanation: "Every element is an even number obtainable as 2 times a natural number from 1 to 5 — exactly the defining property for set-builder notation.",
      reteach: "Look for the pattern connecting all the elements (here, each is 2× a counting number), then express that pattern as a condition inside {x : condition}.",
      hint: "What do all the numbers have in common — think multiples.",
      xp: 20,
    },
    {
      id: "math-t1-l4a",
      bloomLevel: 4,
      type: "mcq",
      prompt: "In a survey of 100 people: 40 read newspaper A, 35 read newspaper B, 20 read both, and 30 say they read neither. Is this data consistent?",
      options: ["Yes, consistent", "No — the numbers don't add up to 100", "No — too many read both", "Cannot be determined"],
      correctAnswer: "No — the numbers don't add up to 100",
      explanation: "n(A∪B) = 40+35−20 = 55 read at least one newspaper. Adding the 30 who read neither gives 85, not 100 — so 15 people are unaccounted for, meaning the data is inconsistent.",
      reteach: "Break this into two checks: compute n(A∪B) with the union formula, then verify n(A∪B) + n(neither) equals the total surveyed. If it doesn't match, the data is inconsistent.",
      hint: "Compute n(A∪B) first, then check if adding 'neither' gives exactly 100.",
      xp: 25,
    },
    {
      id: "math-t1-l4b",
      bloomLevel: 4,
      type: "short-answer",
      prompt: "Using De Morgan's law, explain why 'students who play neither cricket nor football' is the same group as (A ∪ B)′ and as A′ ∩ B′.",
      correctAnswer: "'Neither cricket nor football' means NOT(cricket OR football) = (A∪B)′, which is the same as 'not cricket' AND 'not football' simultaneously = A′∩B′ — both phrases describe the same students.",
      explanation: "De Morgan's law is careful logical language: 'not (X or Y)' always means 'not X AND not Y'. A student who plays neither sport must simultaneously not play cricket and not play football.",
      reteach: "Translate the set notation into plain English first: (A∪B)′ = 'not in A or B' = 'plays neither'. A′∩B′ = 'not in A' AND 'not in B'. Once in plain English, both describe the same group.",
      hint: "Try rephrasing both sides in plain English before comparing them.",
      xp: 25,
    },
  ],
  "math-t5": [
    {
      id: "math-t5-l1",
      bloomLevel: 1,
      type: "mcq",
      prompt: "In a right triangle, tan θ is defined as:",
      options: ["Opposite/Hypotenuse", "Adjacent/Hypotenuse", "Opposite/Adjacent", "Hypotenuse/Adjacent"],
      correctAnswer: "Opposite/Adjacent",
      explanation: "tan θ = opposite side / adjacent side, relative to angle θ in a right triangle.",
      reteach: "Use SOH-CAH-TOA: Sine=Opp/Hyp, Cosine=Adj/Hyp, Tangent=Opp/Adj. Tangent never involves the hypotenuse.",
      hint: "Recall the mnemonic SOH-CAH-TOA.",
      xp: 10,
    },
    {
      id: "math-t5-l2",
      bloomLevel: 2,
      type: "fill-blank",
      prompt: "sin²θ + cos²θ = ___",
      correctAnswer: "1",
      explanation: "This is the fundamental Pythagorean trigonometric identity, derived from the Pythagorean theorem.",
      reteach: "This identity always equals 1 for ANY angle θ — it comes from a² + b² = c² divided by c² in a right triangle.",
      hint: "It's the most fundamental trig identity — think Pythagoras.",
      xp: 15,
    },
    {
      id: "math-t5-l3",
      bloomLevel: 3,
      type: "mcq",
      prompt: "If sin θ = 3/5 and θ is acute, what is cos θ?",
      options: ["4/5", "3/4", "5/4", "1/5"],
      correctAnswer: "4/5",
      explanation: "Using sin²θ + cos²θ = 1: (3/5)² + cos²θ = 1 → cos²θ = 16/25 → cos θ = 4/5 (positive since θ is acute).",
      reteach: "Rearrange to cos²θ = 1 − sin²θ, substitute the given sine value, then take the square root — check the sign based on the quadrant.",
      hint: "Use sin²θ + cos²θ = 1 and solve for cos θ.",
      xp: 20,
    },
    {
      id: "math-t5-l4",
      bloomLevel: 4,
      type: "short-answer",
      prompt: "A tower's angle of elevation from a point 50 m away is 30°. Using tan 30° = 1/√3, find the height and explain your reasoning.",
      correctAnswer: "Height = 50 × tan 30° = 50/√3 ≈ 28.87 m",
      explanation: "The height and the 50 m distance form the two legs of a right triangle with the angle of elevation at the base. tan(angle) = opposite/adjacent = height/distance, so height = 50 × (1/√3) ≈ 28.87 m.",
      reteach: "Draw the right triangle: tower height is 'opposite', ground distance is 'adjacent'. Since tan θ = opposite/adjacent, solve for the opposite side.",
      hint: "Set up tan(30°) = height / 50, then solve for height.",
      xp: 25,
    },
  ],
  "math-t9": [
    {
      id: "math-t9-l1",
      bloomLevel: 1,
      type: "true-false",
      prompt: "In the AP 5, 8, 11, 14, the common difference is 3.",
      correctAnswer: "True",
      explanation: "Each term increases by exactly 3 (8−5=3, 11−8=3, 14−11=3), confirming d = 3.",
      reteach: "To find the common difference, subtract any term from the one right after it. If it's the same throughout, that's your d.",
      hint: "Subtract consecutive terms and compare.",
      xp: 10,
    },
    {
      id: "math-t9-l2",
      bloomLevel: 2,
      type: "fill-blank",
      prompt: "The nth term formula of an AP is aₙ = a + ___",
      correctAnswer: "(n-1)d",
      explanation: "The nth term formula is aₙ = a + (n−1)d, where a is the first term and d is the common difference.",
      reteach: "To reach the nth term from the first term, you take (n−1) 'steps' of size d, since the 1st term requires zero steps.",
      hint: "How many 'steps' of size d do you take to reach the nth term?",
      xp: 15,
    },
    {
      id: "math-t9-l3",
      bloomLevel: 3,
      type: "mcq",
      prompt: "Find the 10th term of the AP 4, 9, 14, 19, ...",
      options: ["49", "44", "54", "39"],
      correctAnswer: "49",
      explanation: "a=4, d=5. Using aₙ=a+(n−1)d: a₁₀ = 4 + 9(5) = 49.",
      reteach: "First find a and d from the sequence, then substitute n=10 into aₙ = a + (n−1)d carefully.",
      hint: "a=4, d=5. Use aₙ = a + (n−1)d with n=10.",
      xp: 20,
    },
    {
      id: "math-t9-l4",
      bloomLevel: 4,
      type: "short-answer",
      prompt: "The sum of the first 10 terms of an AP is 95, and the first term is 5. Find the common difference and explain your method.",
      correctAnswer: "d = 1",
      explanation: "Using Sₙ=n/2[2a+(n−1)d]: 95 = 5[10+9d] → 19 = 10+9d → 9d = 9 → d = 1.",
      reteach: "Substitute all known values (Sₙ, n, a) into Sₙ = n/2[2a+(n−1)d], then solve the resulting linear equation for d step by step.",
      hint: "Plug into Sₙ = n/2[2a+(n−1)d] and solve for d.",
      xp: 25,
    },
  ],
  "phy-t5": [
    {
      id: "phy-t5-l1a",
      bloomLevel: 1,
      type: "mcq",
      prompt: "Which of these is a vector quantity?",
      options: ["Distance", "Speed", "Displacement", "Time"],
      correctAnswer: "Displacement",
      explanation: "Displacement has both magnitude and direction, making it a vector. Distance, speed, and time are scalars.",
      reteach: "Ask: does the quantity need a direction to be fully described? Displacement changes if you go the 'same distance' in a different direction — that's the mark of a vector.",
      hint: "Which quantity depends on direction, not just magnitude?",
      xp: 10,
    },
    {
      id: "phy-t5-l1b",
      bloomLevel: 1,
      type: "true-false",
      prompt: "Speed can never be negative, but velocity can be negative.",
      correctAnswer: "True",
      explanation: "Speed is a scalar magnitude, always ≥0. Velocity is a vector, so it can be negative depending on the chosen direction convention.",
      reteach: "Speed is just 'how fast', always positive. Velocity includes direction, so motion opposite to your chosen positive direction gives a negative velocity value.",
      hint: "Does direction affect the sign of speed, or only of velocity?",
      xp: 10,
    },
    {
      id: "phy-t5-l2a",
      bloomLevel: 2,
      type: "mcq",
      prompt: "On a velocity-time graph, the slope at any point represents:",
      options: ["Displacement", "Distance", "Acceleration", "Speed"],
      correctAnswer: "Acceleration",
      explanation: "Slope = change in velocity / change in time = acceleration, by definition.",
      reteach: "Slope of a position-time graph = velocity; slope of a velocity-time graph = acceleration. It's one level of 'rate of change' higher each time.",
      hint: "What does the slope of a v-t graph represent?",
      xp: 15,
    },
    {
      id: "phy-t5-l2b",
      bloomLevel: 2,
      type: "fill-blank",
      prompt: "The area under a velocity-time graph represents the object's ___",
      correctAnswer: "displacement",
      explanation: "Since velocity × time = displacement, the area under a v-t graph gives total displacement.",
      reteach: "Area under a graph = (y-axis quantity) × (x-axis quantity). Here that's velocity × time = displacement.",
      hint: "Multiply the y-axis quantity (velocity) by the x-axis quantity (time).",
      xp: 15,
    },
    {
      id: "phy-t5-l3a",
      bloomLevel: 3,
      type: "mcq",
      prompt: "A body moving at 10 m/s accelerates at 2 m/s² for 5 s. What is its final velocity?",
      options: ["20 m/s", "15 m/s", "12 m/s", "25 m/s"],
      correctAnswer: "20 m/s",
      explanation: "v=u+at = 10+(2)(5) = 20 m/s.",
      reteach: "Identify u, a, and t from the problem, then plug directly into v = u + at.",
      hint: "Use v = u + at.",
      xp: 20,
    },
    {
      id: "phy-t5-l3b",
      bloomLevel: 3,
      type: "short-answer",
      prompt: "A stone is dropped from a height and takes 3 seconds to hit the ground. Find the height (g=10 m/s²) and justify the equation used.",
      correctAnswer: "Height = 45 m",
      explanation: "Since 'dropped' means u=0, s=ut+½at² gives s=0+½(10)(9)=45 m. This equation is the natural choice when time is given and displacement is needed.",
      reteach: "'Dropped' always means u=0. Choose s=ut+½at² whenever time is given and you need displacement.",
      hint: "u=0 since it's dropped. Use s=ut+½at².",
      xp: 20,
    },
    {
      id: "phy-t5-l4a",
      bloomLevel: 4,
      type: "mcq",
      prompt: "Two cars A and B move in the same direction. Car A has velocity 20 m/s and Car B has velocity 15 m/s. What is the velocity of A relative to B?",
      options: ["5 m/s", "35 m/s", "20 m/s", "15 m/s"],
      correctAnswer: "5 m/s",
      explanation: "Relative velocity of A w.r.t. B = vA − vB = 20−15 = 5 m/s.",
      reteach: "Relative velocity of A w.r.t. B is always vA − vB. Since both move in the same direction, it's a simple subtraction.",
      hint: "Relative velocity = vA − vB.",
      xp: 25,
    },
    {
      id: "phy-t5-l4b",
      bloomLevel: 4,
      type: "short-answer",
      prompt: "A ball thrown vertically upward returns to the thrower's hand after 4 seconds. Find the maximum height and initial velocity (g=10 m/s²).",
      correctAnswer: "u = 20 m/s, max height = 20 m",
      explanation: "By symmetry, time up = 2 s. At the peak v=0, so v=u+at gives 0=u−20, u=20 m/s. Then v²=u²+2as gives 0=400−20s, s=20 m.",
      reteach: "Break the motion into symmetric halves using total flight time. At the top, velocity=0 — use v=u+at to find u, then v²=u²+2as for max height.",
      hint: "Use symmetry: time up = total time / 2, and velocity = 0 at the highest point.",
      xp: 25,
    },
  ],
  "phy-t10": [
    {
      id: "phy-t10-l1",
      bloomLevel: 1,
      type: "mcq",
      prompt: "Newton's Second Law is best summarized by which equation?",
      options: ["F = ma", "F = mv", "p = Fv", "a = Fv"],
      correctAnswer: "F = ma",
      explanation: "For constant mass, Newton's Second Law simplifies to F = ma — net force equals mass times acceleration.",
      reteach: "Newton's Second Law connects force, mass, and acceleration: force causes acceleration, and heavier objects need more force for the same acceleration.",
      hint: "Which equation directly relates force, mass, and acceleration?",
      xp: 10,
    },
    {
      id: "phy-t10-l2",
      bloomLevel: 2,
      type: "fill-blank",
      prompt: "If mass is constant, F = ma shows acceleration is directly proportional to ___",
      correctAnswer: "force",
      explanation: "a = F/m shows acceleration increases when force increases (direct proportionality) and decreases when mass increases.",
      reteach: "Rearrange F=ma into a=F/m. Whatever is in the numerator (force) is 'directly proportional'.",
      hint: "Rearrange F=ma to solve for a.",
      xp: 15,
    },
    {
      id: "phy-t10-l3",
      bloomLevel: 3,
      type: "mcq",
      prompt: "A net force of 15 N acts on an object, producing an acceleration of 3 m/s². What is the object's mass?",
      options: ["5 kg", "45 kg", "0.2 kg", "18 kg"],
      correctAnswer: "5 kg",
      explanation: "Using F=ma, m = F/a = 15/3 = 5 kg.",
      reteach: "Rearrange F=ma to isolate mass: m = F/a, then substitute carefully.",
      hint: "Rearrange F = ma to solve for m.",
      xp: 20,
    },
    {
      id: "phy-t10-l4",
      bloomLevel: 4,
      type: "short-answer",
      prompt: "A 2 kg block on a frictionless surface is pushed with 8 N while a 3 N opposing force acts on it. Find the resulting acceleration and explain how you accounted for both forces.",
      correctAnswer: "a = 2.5 m/s²",
      explanation: "Net force = 8 − 3 = 5 N. a = F_net/m = 5/2 = 2.5 m/s². Newton's Second Law uses the NET force, not just one applied force.",
      reteach: "Always find the NET force first by adding/subtracting all forces, then apply F_net = ma. Forgetting to subtract opposing forces is a common mistake.",
      hint: "Find the net force first (subtract opposing forces), then use F=ma.",
      xp: 25,
    },
  ],
  "phy-t12": [
    {
      id: "phy-t12-l1",
      bloomLevel: 1,
      type: "true-false",
      prompt: "Kinetic friction is generally slightly less than the maximum static friction between the same two surfaces.",
      correctAnswer: "True",
      explanation: "Once an object starts moving, kinetic friction (μₖN) is usually slightly less than the maximum static friction (μₛN), since μₖ < μₛ typically.",
      reteach: "It takes more force to get a heavy box MOVING (static friction) than to keep it moving at constant speed (kinetic friction) — because μₛ > μₖ generally.",
      hint: "Which is usually needed more: starting motion or maintaining it?",
      xp: 10,
    },
    {
      id: "phy-t12-l2",
      bloomLevel: 2,
      type: "fill-blank",
      prompt: "The formula for kinetic friction force is f_k = ___ × N",
      correctAnswer: "μk",
      explanation: "f_k = μₖN, where μₖ is the coefficient of kinetic friction and N is the normal force.",
      reteach: "Friction force is always the coefficient of friction (μ) multiplied by the normal force (N). For a moving object, use μₖ.",
      hint: "What symbol represents the coefficient of kinetic friction?",
      xp: 15,
    },
    {
      id: "phy-t12-l3",
      bloomLevel: 3,
      type: "mcq",
      prompt: "A 20 kg crate has μₖ = 0.25 with the floor. Find the kinetic friction force (g=10 m/s²).",
      options: ["50 N", "20 N", "200 N", "5 N"],
      correctAnswer: "50 N",
      explanation: "N = mg = 20×10 = 200 N. f_k = μₖN = 0.25×200 = 50 N.",
      reteach: "First calculate the normal force N = mg, then multiply by μₖ to get the friction force.",
      hint: "First find N = mg, then use f_k = μₖN.",
      xp: 20,
    },
    {
      id: "phy-t12-l4",
      bloomLevel: 4,
      type: "short-answer",
      prompt: "A block just begins to slide down a ramp when the incline angle reaches 25°. Explain what this tells you about the coefficient of static friction, and calculate its approximate value.",
      correctAnswer: "μs ≈ 0.47",
      explanation: "At the angle of repose, gravity's component along the incline exactly equals the maximum static friction: tan θ = μₛ, so μₛ = tan 25° ≈ 0.466.",
      reteach: "The angle at which an object JUST starts to slide under its own weight is the angle of repose, satisfying tan θ = μₛ.",
      hint: "Use the angle of repose relation: tan θ = μₛ.",
      xp: 25,
    },
  ],
};

function genericQuestions(topicId: string, topicName: string, chapterName: string): LessonQuestion[] {
  return [
    {
      id: `${topicId}-l1a`,
      bloomLevel: 1,
      type: "true-false",
      prompt: `${topicName} is introduced within the "${chapterName}" chapter of your syllabus.`,
      correctAnswer: "True",
      explanation: `Yes — ${topicName} is one of the topics grouped under ${chapterName}.`,
      reteach: `Check your chapter list — ${topicName} sits within ${chapterName}.`,
      hint: "Think about which chapter this topic belongs to.",
      xp: 10,
    },
    {
      id: `${topicId}-l1b`,
      bloomLevel: 1,
      type: "fill-blank",
      prompt: `Complete the sentence: "Understanding ___ is the main goal of this lesson." (Type the topic name.)`,
      correctAnswer: topicName,
      explanation: `This lesson is entirely focused on building a solid understanding of ${topicName}.`,
      reteach: `The missing word is simply the topic you're studying: ${topicName}.`,
      hint: "The missing word is the name of the topic itself.",
      xp: 10,
    },
    {
      id: `${topicId}-l2a`,
      bloomLevel: 2,
      type: "true-false",
      prompt: `A good first step to understanding ${topicName} is reviewing its definition and any related formulae before attempting problems.`,
      correctAnswer: "True",
      explanation: "Understanding always starts with the definition and core formula, before moving on to application.",
      reteach: "Revisit the Theory and Key Formulae sections of this topic before attempting more advanced questions.",
      hint: "Does understanding usually come before application?",
      xp: 15,
    },
    {
      id: `${topicId}-l2b`,
      bloomLevel: 2,
      type: "short-answer",
      prompt: `In 1-2 sentences, explain the core idea of ${topicName} in your own words.`,
      correctAnswer: topicName,
      explanation: `A good explanation of ${topicName} references its definition and how it fits within ${chapterName}.`,
      reteach: "Review the Theory tab for this topic, then try rephrasing the first paragraph in your own words.",
      hint: "Start with 'the main idea of this topic is...'",
      xp: 15,
    },
    {
      id: `${topicId}-l3a`,
      bloomLevel: 3,
      type: "true-false",
      prompt: `Applying ${topicName} correctly usually requires identifying the given information before choosing the right formula or rule.`,
      correctAnswer: "True",
      explanation: "Application-level questions require first extracting the relevant given values, then matching them to the correct rule or formula.",
      reteach: "Practice re-reading application questions and listing out 'what is given' and 'what is asked' before attempting a solution.",
      hint: "Does identifying the given data come before applying a formula?",
      xp: 20,
    },
    {
      id: `${topicId}-l3b`,
      bloomLevel: 3,
      type: "short-answer",
      prompt: `Describe a real-world situation where ${topicName} would be useful, and briefly explain why.`,
      correctAnswer: topicName,
      explanation: `${topicName} connects to real applications — review the Applications tab of this topic for concrete examples.`,
      reteach: "Check the Real-life Applications section of this topic's content page for inspiration.",
      hint: "Think about where this concept might show up outside the classroom.",
      xp: 20,
    },
    {
      id: `${topicId}-l4a`,
      bloomLevel: 4,
      type: "true-false",
      prompt: `Analytical questions on ${topicName} often require combining multiple ideas from ${chapterName}, not just one formula.`,
      correctAnswer: "True",
      explanation: "Analysis-level (Bloom Level 4) questions typically require synthesizing more than one idea or verifying consistency between given facts.",
      reteach: "When a question feels harder than usual, check whether it's really combining two or more concepts from the chapter.",
      hint: "Do harder questions usually rely on just one isolated fact?",
      xp: 25,
    },
    {
      id: `${topicId}-l4b`,
      bloomLevel: 4,
      type: "short-answer",
      prompt: `Explain, using reasoning rather than just recall, why ${topicName} is an important building block for the rest of "${chapterName}".`,
      correctAnswer: topicName,
      explanation: `${topicName} typically underpins later ideas in ${chapterName} — review the Summary and Revision Notes tabs to see these connections explicitly.`,
      reteach: "Reread the Summary tab, then try to describe in your own words how this topic connects to at least one other topic in the same chapter.",
      hint: "Think about which later topics in this chapter might depend on this one.",
      xp: 25,
    },
  ];
}

export function getLessonPlan(subjectSlug: string, topicSlug: string): LessonPlan | null {
  const found = getTopicContent(subjectSlug, topicSlug);
  if (!found) return null;
  const { topic, chapter, content } = found;
  const questions = authoredLessons[topic.id] ?? genericQuestions(topic.id, topic.name, chapter.name);
  return {
    topicId: topic.id,
    recap: content.summary,
    examples: content.examples,
    questions,
  };
}

// Lenient mock-grading for lesson answers. MCQ/true-false use exact match;
// fill-blank uses a forgiving case-insensitive substring match; short-answer
// checks for a meaningful keyword overlap so the demo never feels broken.
export function isLessonAnswerCorrect(question: LessonQuestion, studentAnswer: string): boolean {
  const answer = studentAnswer.trim().toLowerCase();
  if (!answer) return false;
  const correct = question.correctAnswer.trim().toLowerCase();

  if (question.type === "mcq" || question.type === "true-false") {
    return answer === correct;
  }

  if (question.type === "fill-blank") {
    const normalize = (s: string) => s.replace(/[{}()\s]/g, "");
    return normalize(answer).includes(normalize(correct)) || normalize(correct).includes(normalize(answer));
  }

  // short-answer: lenient keyword-based check
  const keywords = correct
    .replace(/[^a-z0-9.\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length > 2);
  if (keywords.length === 0) return answer.length > 10;
  const hits = keywords.filter((k) => answer.includes(k)).length;
  return hits > 0 || answer.length > 25;
}
