import { PracticeTest } from "@/lib/types";

export const practiceTests: PracticeTest[] = [
  {
    id: "pt-1",
    title: "Mathematics Full Syllabus Mock #3",
    subject: "Mathematics",
    dateTaken: "2026-07-15",
    score: 78,
    maxScore: 100,
    questionCount: 50,
    durationMinutes: 90,
    status: "completed",
  },
  {
    id: "pt-2",
    title: "Physics Chapter Test: Kinematics",
    subject: "Physics",
    dateTaken: "2026-07-11",
    score: 88,
    maxScore: 100,
    questionCount: 30,
    durationMinutes: 45,
    status: "completed",
  },
  {
    id: "pt-3",
    title: "Chemistry Redox & Bonding",
    subject: "Chemistry",
    maxScore: 100,
    questionCount: 40,
    durationMinutes: 60,
    status: "not-started",
  },
  {
    id: "pt-4",
    title: "Biology Cell Structure Quiz",
    subject: "Biology",
    dateTaken: "2026-07-08",
    score: 91,
    maxScore: 100,
    questionCount: 25,
    durationMinutes: 30,
    status: "completed",
  },
  {
    id: "pt-5",
    title: "English Comprehension Practice Set",
    subject: "English",
    maxScore: 50,
    questionCount: 20,
    durationMinutes: 40,
    status: "not-started",
  },
];
