import { WeakConcept } from "@/lib/types";

// Weak concepts are pulled from the same weakTopics already established in
// lib/mock-data/subjects.ts (Permutations, Ellipse & Hyperbola, Dimensional
// Analysis, Friction, Redox Reactions, Biomolecules, Note Making) so this
// page stays perfectly consistent with Subjects -> Chapters -> Topics.
export const weakConcepts: WeakConcept[] = [
  {
    id: "wc-1",
    subject: "Mathematics",
    subjectColor: "indigo",
    chapter: "Permutations & Combinations",
    topic: "Permutations",
    bloomLevel: "Apply",
    reason: "3 wrong answers in the last Permutations & Combinations quiz - Level 3 Apply",
    wrongAnswers: 3,
    totalAttempts: 8,
    mastery: 38,
    trend: "improving",
    trendHistory: [22, 26, 30, 34, 38],
    lastPracticed: "2026-07-16",
    relatedSubjectSlug: "mathematics",
    relatedTopicSlug: "permutations",
  },
  {
    id: "wc-2",
    subject: "Mathematics",
    subjectColor: "indigo",
    chapter: "Conic Sections",
    topic: "Ellipse & Hyperbola",
    bloomLevel: "Apply",
    reason: "5 wrong answers in Chapter Test - Level 3 Apply questions on eccentricity",
    wrongAnswers: 5,
    totalAttempts: 9,
    mastery: 22,
    trend: "declining",
    trendHistory: [35, 30, 27, 24, 22],
    lastPracticed: "2026-07-10",
    relatedSubjectSlug: "mathematics",
    relatedTopicSlug: "ellipse-and-hyperbola",
  },
  {
    id: "wc-3",
    subject: "Mathematics",
    subjectColor: "indigo",
    chapter: "Conic Sections",
    topic: "Parabola",
    bloomLevel: "Understand",
    reason: "Mastery below 40% - directrix/focus concepts not yet retained",
    wrongAnswers: 2,
    totalAttempts: 6,
    mastery: 38,
    trend: "stable",
    trendHistory: [40, 39, 37, 38, 38],
    lastPracticed: "2026-07-12",
    relatedSubjectSlug: "mathematics",
    relatedTopicSlug: "parabola",
  },
  {
    id: "wc-4",
    subject: "Physics",
    subjectColor: "sky",
    chapter: "Units & Measurement",
    topic: "Dimensional Analysis",
    bloomLevel: "Understand",
    reason: "Not revisited in 14 days and 3 wrong answers in last practice set",
    wrongAnswers: 3,
    totalAttempts: 7,
    mastery: 45,
    trend: "stable",
    trendHistory: [48, 47, 46, 45, 45],
    lastPracticed: "2026-07-05",
    relatedSubjectSlug: "physics",
    relatedTopicSlug: "dimensional-analysis",
  },
  {
    id: "wc-5",
    subject: "Physics",
    subjectColor: "sky",
    chapter: "Laws of Motion",
    topic: "Friction",
    bloomLevel: "Apply",
    reason: "4 wrong answers in Laws of Motion problem set - Level 3 Apply",
    wrongAnswers: 4,
    totalAttempts: 10,
    mastery: 48,
    trend: "improving",
    trendHistory: [30, 35, 40, 44, 48],
    lastPracticed: "2026-07-17",
    relatedSubjectSlug: "physics",
    relatedTopicSlug: "friction",
  },
  {
    id: "wc-6",
    subject: "Physics",
    subjectColor: "sky",
    chapter: "Rotational Motion",
    topic: "Moment of Inertia",
    bloomLevel: "Understand",
    reason: "Newly introduced topic - low mastery, needs first full revision cycle",
    wrongAnswers: 1,
    totalAttempts: 3,
    mastery: 25,
    trend: "stable",
    trendHistory: [25, 24, 25, 25, 25],
    lastPracticed: "2026-07-08",
    relatedSubjectSlug: "physics",
    relatedTopicSlug: "moment-of-inertia",
  },
  {
    id: "wc-7",
    subject: "Chemistry",
    subjectColor: "emerald",
    chapter: "Redox Reactions",
    topic: "Balancing Redox Equations",
    bloomLevel: "Apply",
    reason: "6 wrong answers across two practice papers - Level 3 Apply",
    wrongAnswers: 6,
    totalAttempts: 11,
    mastery: 30,
    trend: "declining",
    trendHistory: [42, 38, 35, 32, 30],
    lastPracticed: "2026-07-09",
    relatedSubjectSlug: "chemistry",
    relatedTopicSlug: "balancing-redox-equations",
  },
  {
    id: "wc-8",
    subject: "Chemistry",
    subjectColor: "emerald",
    chapter: "Redox Reactions",
    topic: "Oxidation Numbers",
    bloomLevel: "Understand",
    reason: "Low score (52%) on last practice test covering oxidation states",
    wrongAnswers: 3,
    totalAttempts: 8,
    mastery: 45,
    trend: "improving",
    trendHistory: [30, 34, 38, 42, 45],
    lastPracticed: "2026-07-15",
    relatedSubjectSlug: "chemistry",
    relatedTopicSlug: "oxidation-numbers",
  },
  {
    id: "wc-9",
    subject: "Chemistry",
    subjectColor: "emerald",
    chapter: "Chemical Bonding",
    topic: "Hybridization",
    bloomLevel: "Understand",
    reason: "New chapter - orbital hybridization diagrams frequently misread",
    wrongAnswers: 2,
    totalAttempts: 5,
    mastery: 40,
    trend: "stable",
    trendHistory: [40, 41, 39, 40, 40],
    lastPracticed: "2026-07-11",
    relatedSubjectSlug: "chemistry",
    relatedTopicSlug: "hybridization",
  },
  {
    id: "wc-10",
    subject: "Biology",
    subjectColor: "rose",
    chapter: "Cell: Structure & Function",
    topic: "Biomolecules",
    bloomLevel: "Analyze",
    reason: "3 wrong answers in Cell Structure quiz - Level 4 Analyze on enzyme structure",
    wrongAnswers: 3,
    totalAttempts: 7,
    mastery: 42,
    trend: "improving",
    trendHistory: [28, 32, 36, 39, 42],
    lastPracticed: "2026-07-14",
    relatedSubjectSlug: "biology",
    relatedTopicSlug: "biomolecules",
  },
  {
    id: "wc-11",
    subject: "English",
    subjectColor: "amber",
    chapter: "Writing Skills",
    topic: "Note Making",
    bloomLevel: "Apply",
    reason: "Consistently loses marks on abbreviation format and hierarchy of points",
    wrongAnswers: 2,
    totalAttempts: 6,
    mastery: 52,
    trend: "declining",
    trendHistory: [60, 58, 56, 54, 52],
    lastPracticed: "2026-07-13",
    relatedSubjectSlug: "english",
    relatedTopicSlug: "note-making",
  },
];

export function weakConceptsBySubject() {
  const map = new Map<string, WeakConcept[]>();
  for (const wc of weakConcepts) {
    const list = map.get(wc.subject) ?? [];
    list.push(wc);
    map.set(wc.subject, list);
  }
  return map;
}
