import type { LucideIcon, LucideProps } from "lucide-react";
import {
  LayoutDashboard,
  BookOpen,
  CalendarClock,
  ClipboardList,
  FileText,
  TrendingUp,
  Target,
  Trophy,
  Calendar,
  MessageCircleQuestion,
  Settings,
  Sigma,
  Atom,
  FlaskConical,
  Dna,
  BookOpenText,
  Footprints,
  Flame,
  Zap,
  BrainCircuit,
  Crown,
  Users,
  Sunrise,
  PenTool,
  RotateCcw,
  HelpCircle,
  ListChecks,
  Rocket,
  Moon,
  CalendarCheck2,
  CheckCircle2,
  Percent,
  Gauge,
  ShieldCheck,
  ClipboardCheck,
  BarChart3,
  GraduationCap,
  Database,
  Server,
} from "lucide-react";

// Explicit registry (rather than `import * as` from lucide-react) so
// production bundles only include the icons actually used in the app.
const iconRegistry: Record<string, LucideIcon> = {
  LayoutDashboard,
  BookOpen,
  CalendarClock,
  ClipboardList,
  FileText,
  TrendingUp,
  Target,
  Trophy,
  Calendar,
  MessageCircleQuestion,
  Settings,
  Sigma,
  Atom,
  FlaskConical,
  Dna,
  BookOpenText,
  Footprints,
  Flame,
  Zap,
  BrainCircuit,
  Crown,
  Users,
  Sunrise,
  PenTool,
  RotateCcw,
  HelpCircle,
  ListChecks,
  Rocket,
  Moon,
  CalendarCheck2,
  CheckCircle2,
  Percent,
  Gauge,
  ShieldCheck,
  ClipboardCheck,
  BarChart3,
  GraduationCap,
  Database,
  Server,
};

export function DynamicIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = iconRegistry[name] ?? HelpCircle;
  return <Icon {...props} />;
}
